export interface LeaderboardPlayer {
  rank: number;
  name: string;
  username: string;
  title?: "GM" | "IM" | "FM" | "WGM" | "CM";
  avatarColor: string;
  avatarUrl?: string;
  country: string;
  flag: string;
  rating: number;
  change: number;
  gamesWon: number;
  gamesLost: number;
  gamesDrawn: number;
  winRate: number;
  recentForm: ("W" | "D" | "L")[];
  bestWin: string;
}

export type LeaderboardCategory = "blitz" | "rapid" | "bullet" | "puzzles" | "ai_slayers";
export type LeaderboardTimeFrame = "this_week" | "this_month" | "all_time";

export const LEADERBOARD_PLAYERS: Record<LeaderboardCategory, LeaderboardPlayer[]> = {
  blitz: [
    {
      rank: 1,
      name: "Lê Quang Liêm",
      username: "LeQuangLiem_VN",
      title: "GM",
      avatarColor: "#2563eb",
      avatarUrl: "/avatars/le_quang_liem.jpg",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2785,
      change: 24,
      gamesWon: 142,
      gamesLost: 18,
      gamesDrawn: 24,
      winRate: 88,
      recentForm: ["W", "W", "W", "D", "W"],
      bestWin: "Vô địch Thế Giới Cờ Chớp FIDE",
    },
    {
      rank: 2,
      name: "Magnus Carlsen",
      username: "Magnus_Ghost",
      title: "GM",
      avatarColor: "#eab308",
      avatarUrl: "/avatars/magnus_carlsen.jpg",
      country: "Na Uy",
      flag: "🇳🇴",
      rating: 2882,
      change: 12,
      gamesWon: 310,
      gamesLost: 32,
      gamesDrawn: 48,
      winRate: 89,
      recentForm: ["W", "W", "D", "W", "W"],
      bestWin: "5 Lần Vô Địch Thế Giới",
    },
    {
      rank: 3,
      name: "Hikaru Nakamura",
      username: "Hikaru_Speed",
      title: "GM",
      avatarColor: "#ef4444",
      avatarUrl: "/avatars/hikaru_nakamura.jpg",
      country: "Hoa Kỳ",
      flag: "🇺🇸",
      rating: 2860,
      change: 18,
      gamesWon: 290,
      gamesLost: 35,
      gamesDrawn: 40,
      winRate: 86,
      recentForm: ["W", "W", "W", "W", "D"],
      bestWin: "Đệ Nhất Kỳ Thủ Speed Chess",
    },
    {
      rank: 4,
      name: "Nguyễn Ngọc Trường Sơn",
      username: "TruongSon_Master",
      title: "GM",
      avatarColor: "#059669",
      avatarUrl: "/avatars/truong_son.jpg",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2680,
      change: 15,
      gamesWon: 110,
      gamesLost: 20,
      gamesDrawn: 22,
      winRate: 81,
      recentForm: ["W", "D", "W", "W", "W"],
      bestWin: "Huy Chương Vàng SEA Games",
    },
    {
      rank: 5,
      name: "Alireza Firouzja",
      username: "Alireza_Storm",
      title: "GM",
      avatarColor: "#9333ea",
      country: "Pháp",
      flag: "🇫🇷",
      rating: 2805,
      change: -4,
      gamesWon: 195,
      gamesLost: 38,
      gamesDrawn: 30,
      winRate: 80,
      recentForm: ["W", "L", "W", "W", "D"],
      bestWin: "Vô địch Grand Chess Tour",
    },
    {
      rank: 6,
      name: "Trần Minh Tuấn",
      username: "Tuan_Dragon",
      title: "IM",
      avatarColor: "#d97706",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2490,
      change: 32,
      gamesWon: 92,
      gamesLost: 24,
      gamesDrawn: 18,
      winRate: 76,
      recentForm: ["W", "W", "W", "D", "W"],
      bestWin: "Top 1 Giải Mùa Thu 2026",
    },
    {
      rank: 7,
      name: "Đặng Hoàng Bách",
      username: "Bach_ChessNinja",
      title: "FM",
      avatarColor: "#0891b2",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2360,
      change: 20,
      gamesWon: 84,
      gamesLost: 28,
      gamesDrawn: 12,
      winRate: 72,
      recentForm: ["W", "W", "L", "W", "W"],
      bestWin: "Chuỗi 12 trận bất bại",
    },
    {
      rank: 8,
      name: "Võ Thị Kim Phụng",
      username: "KimPhung_Queen",
      title: "WGM",
      avatarColor: "#ec4899",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2355,
      change: 11,
      gamesWon: 79,
      gamesLost: 25,
      gamesDrawn: 16,
      winRate: 71,
      recentForm: ["D", "W", "W", "W", "D"],
      bestWin: "Vô địch Châu Á Nữ",
    },
  ],
  rapid: [
    {
      rank: 1,
      name: "Magnus Carlsen",
      username: "Magnus_Ghost",
      title: "GM",
      avatarColor: "#eab308",
      avatarUrl: "/avatars/magnus_carlsen.jpg",
      country: "Na Uy",
      flag: "🇳🇴",
      rating: 2895,
      change: 8,
      gamesWon: 180,
      gamesLost: 12,
      gamesDrawn: 35,
      winRate: 91,
      recentForm: ["W", "W", "W", "D", "W"],
      bestWin: "World Rapid Champion 2025",
    },
    {
      rank: 2,
      name: "Lê Quang Liêm",
      username: "LeQuangLiem_VN",
      title: "GM",
      avatarColor: "#2563eb",
      avatarUrl: "/avatars/le_quang_liem.jpg",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2760,
      change: 19,
      gamesWon: 98,
      gamesLost: 14,
      gamesDrawn: 20,
      winRate: 85,
      recentForm: ["W", "W", "D", "W", "W"],
      bestWin: "Top 15 Thế Giới FIDE",
    },
    {
      rank: 3,
      name: "Gukesh D",
      username: "Gukesh_King",
      title: "GM",
      avatarColor: "#10b981",
      country: "Ấn Độ",
      flag: "🇮🇳",
      rating: 2795,
      change: 28,
      gamesWon: 140,
      gamesLost: 22,
      gamesDrawn: 28,
      winRate: 83,
      recentForm: ["W", "W", "W", "W", "W"],
      bestWin: "Thách đấu Ngôi Vua Cờ 2024",
    },
    {
      rank: 4,
      name: "Nodirbek Abdusattorov",
      username: "Nodirbek_Warrior",
      title: "GM",
      avatarColor: "#6366f1",
      country: "Uzbekistan",
      flag: "🇺🇿",
      rating: 2780,
      change: 14,
      gamesWon: 125,
      gamesLost: 20,
      gamesDrawn: 24,
      winRate: 82,
      recentForm: ["W", "D", "W", "W", "W"],
      bestWin: "Huy Chương Vàng Olympic",
    },
  ],
  bullet: [
    {
      rank: 1,
      name: "Hikaru Nakamura",
      username: "Hikaru_Speed",
      title: "GM",
      avatarColor: "#ef4444",
      avatarUrl: "/avatars/hikaru_nakamura.jpg",
      country: "Hoa Kỳ",
      flag: "🇺🇸",
      rating: 3240,
      change: 35,
      gamesWon: 520,
      gamesLost: 45,
      gamesDrawn: 20,
      winRate: 91,
      recentForm: ["W", "W", "W", "W", "W"],
      bestWin: "Vô Địch Bullet Brawl 50 Tuần",
    },
    {
      rank: 2,
      name: "Daniel Naroditsky",
      username: "Danya_Sensei",
      title: "GM",
      avatarColor: "#3b82f6",
      country: "Hoa Kỳ",
      flag: "🇺🇸",
      rating: 3120,
      change: 22,
      gamesWon: 410,
      gamesLost: 50,
      gamesDrawn: 18,
      winRate: 88,
      recentForm: ["W", "W", "W", "L", "W"],
      bestWin: "Bậc thầy cờ chớp thời gian 1 phút",
    },
    {
      rank: 3,
      name: "Andrew Tang",
      username: "Penguingm1",
      title: "GM",
      avatarColor: "#8b5cf6",
      country: "Hoa Kỳ",
      flag: "🇺🇸",
      rating: 3080,
      change: 16,
      gamesWon: 390,
      gamesLost: 55,
      gamesDrawn: 15,
      winRate: 86,
      recentForm: ["W", "W", "L", "W", "W"],
      bestWin: "Tốc độ di chuột 0.2s/nước",
    },
  ],
  puzzles: [
    {
      rank: 1,
      name: "Trần Thế Phong",
      username: "Phong_Tactician",
      title: "FM",
      avatarColor: "#14b8a6",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 3150,
      change: 45,
      gamesWon: 1450,
      gamesLost: 120,
      gamesDrawn: 0,
      winRate: 92,
      recentForm: ["W", "W", "W", "W", "W"],
      bestWin: "Giải 52 câu đố trong 3 phút (Puzzle Rush)",
    },
    {
      rank: 2,
      name: "ChessMonster_X",
      username: "Monster_X",
      title: "IM",
      avatarColor: "#f59e0b",
      country: "Đức",
      flag: "🇩🇪",
      rating: 3080,
      change: 28,
      gamesWon: 1280,
      gamesLost: 140,
      gamesDrawn: 0,
      winRate: 90,
      recentForm: ["W", "W", "W", "W", "D"],
      bestWin: "Chuỗi 65 câu đố liên tiếp",
    },
  ],
  ai_slayers: [
    {
      rank: 1,
      name: "Phan Anh Quân",
      username: "Quan_BotHunter",
      title: "IM",
      avatarColor: "#ec4899",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2950,
      change: 60,
      gamesWon: 45,
      gamesLost: 12,
      gamesDrawn: 8,
      winRate: 78,
      recentForm: ["W", "W", "W", "D", "W"],
      bestWin: "Hạ gục Stockfish Cấp Siêu AI (2500 ELO)",
    },
    {
      rank: 2,
      name: "Nguyễn Minh Đức",
      username: "Duc_StockfishKiller",
      title: "FM",
      avatarColor: "#3b82f6",
      country: "Việt Nam",
      flag: "🇻🇳",
      rating: 2870,
      change: 42,
      gamesWon: 38,
      gamesLost: 14,
      gamesDrawn: 6,
      winRate: 75,
      recentForm: ["W", "W", "L", "W", "W"],
      bestWin: "Chiến thắng Bot Mikhail Tal & Bobby Fischer",
    },
  ],
};
